name:                cryptopals-tasks
version:             0.1.0.0
github:              "githubuser/cryptopals-tasks"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cryptopals-tasks#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- base64-bytestring
- base16-bytestring
- optparse-applicative
- containers
- split
- cipher-aes128
- hosc >= 0.18.1
- random >= 1.2.0
- aeson
- http-types
- text
- Unique
- ghc-lib-parser
- binary

library:
  source-dirs: src

executables:
  cryptopals-tasks-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cryptopals-tasks

tests:
  cryptopals-tasks-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cryptopals-tasks
